replicasCount: 1

image:
  url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-training-service
  tag: 23.07

environments:
  - name: SERVICE_PRECONDITION
    value: uag-service:8084

mounts:
  - name: training
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: training-service-configmap
  - name: tls
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: kypo-certs

connectionTimeout:
maximumPoolSize:
