{{- with .Values.guacd }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.matchLabels" (dict "name" .name "release" $.Release)  | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 8 }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.url }}:{{ .image.tag }}"
          ports:
            {{- range .ports }}
            - containerPort: {{ .port }}
              name: guacd-{{ .port }}
            {{- end }}
          readinessProbe:
            {{- range .ports }}
            {{- if eq .protocol "TCP" }}
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: data-{{ .name }}
              mountPath: /drive
              subPath: drive
            - name: data-{{ .name }}
              mountPath: /record
              subPath: record
      volumes:
        - name: data-{{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
{{- end }}
