apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--log.level=INFO"
      - "--ping"
      - "--metrics.prometheus"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

    deployment:
      kind: DaemonSet

    # no load balancer
    service:
      enabled: true
      type: ClusterIP

    # use host network for directly port listening
    hostNetwork: true

    ports:
      web:
        port: 80
        protocol: TCP
        exposedPort: 80
      websecure:
        port: 443
        protocol: TCP
        exposedPort: 443
        tls:
          enabled: true
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: null
    # run as root to 80 and 443 port listen permission
    securityContext:
      capabilities:
        add:
          - NET_BIND_SERVICE
      runAsNonRoot: false
      runAsUser: 0
