global:
  acmeContact:
  guacamoleUserPassword:
  headHost:
  oidcProviders:
    - url:
      logoutUrl:
      clientId:
      label:
      issuerIdentifier:
      userInfoUrl:
      responseType:
  users:
    - email: crczp-admin@example.com
      iss:
      fullName: "Demo Admin"
      givenName: "Demo"
      familyName: "Admin"
      admin: True
      keycloakUsername:
      keycloakPassword:
    - email: crczp-user@example.com
      iss:
      fullName: "Demo User"
      givenName: "Demo"
      familyName: "User"
      admin: False
      keycloakUsername:
      keycloakPassword:
  userCount: 0

crczp-guacamole:
  guacamole:
    guacamoleAdminPassword:


sandbox:
  djangoSecretKey:
  headHost:
  stackNamePrefix:
  dnsNameServers:
    - 1.1.1.1
    - 1.0.0.1
  osAuthUrl:
  osApplicationCredentialId:
  osApplicationCredentialSecret:
  proxyHost:
  proxyUser:
  proxyKey:
  gitConfig:
    providers: {}
    #providers: {"https://github.com/": "TOKEN"}
    user: git
    ansibleNetworkingUrl: https://github.com/cyberrangecz/ansible-stage-one.git
    ansibleNetworkingRev: v1.0.0

cluster:
  superuserPassword: password
