{{- with .Values.guacamole }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole-ingress
  labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 4 }}
  {{- if $.Values.global.corsWhitelist }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kypo-guacamole-header@kubernetescrd
  {{- end }}
spec:
  tls:
  - hosts:
      - {{ $.Values.global.headHost }}
    secretName: {{ $.Values.global.tlsSecretName }}
  rules:
    {{- if mustRegexMatch "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.){3}(25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)$" $.Values.global.headHost }}
    - http:
    {{- else }}
    - host: {{ $.Values.global.headHost }}
      http:
    {{- end }}
        paths:
        - path: /guacamole/
          pathType: Prefix
          backend:
            service:
              name: {{ .name }}
              port:
                number: {{ (first .ports).port }}
{{- end }}
