{{- if .Values.keystoneCA }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.services.sandbox.name }}-keystone-ca
  labels: {{- include "common.labels" (dict "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
type: Opaque
data:
  keystone-ca.crt: {{ .Values.keystoneCA }}
{{- end }}
