apiVersion: v1
kind: Secret
metadata:
  name: proxy-key
  labels: {{- include "common.labels" (dict "name" .Values.global.services.sandbox.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
type: Opaque
data:
  proxy-key: {{ .Values.proxyKey }}
