replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-adaptive-training/adaptive-training-service
  tag: v0.0.3

environments:
  - name: SERVICE_PRECONDITION
    value: uag-service:8084

mounts:
  - name: adaptive-training
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: adaptive-training-service-configmap
  - name: tls
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: crczp-certs

connectionTimeout:
maximumPoolSize:
