replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-elasticsearch-service/elasticsearch-service-service
  tag: v0.0.1

environments:
  - name: SERVICE_PRECONDITION
    value: uag-service:8084

mounts:
  - name: elasticsearch-service
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: elasticsearch-service-configmap
  - name: tls
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: crczp-certs
