replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-training-feedback/training-feedback-service
  tag: v1.0.0

mounts:
  training-feedback:
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: training-feedback-service-configmap
  tls:
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: crczp-certs
