apiVersion: v2
name: crczp-redis
description: Redis Helm chart used by head services
type: application
version: 1.0.0
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
