{{- with .Values.guacamole }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole-ingressroute
  labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      {{- if mustRegexMatch "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.){3}(25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)$" $.Values.global.headHost }}
      match: PathPrefix(`/guacamole/`)
      {{- else }}
      match: Host(`{{ $.Values.global.headHost }}`) && PathPrefix(`/guacamole/`)
      {{- end }}
      {{- if $.Values.global.corsWhitelist }}
      middlewares:
        - name: guacamole-header
      {{- end }}
      services:
        - kind: Service
          name: {{ .name }}
          port: {{ (first .ports).port }}
  tls:
    secretName: {{ $.Values.global.tlsSecretName }}
    domains:
    - main: {{ $.Values.global.headHost }}
{{- end }}
