{{- with .Values.guacamole }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  annotations:
    reloader.stakater.com/auto: "true"
  labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 4 }}
spec:
  replicas: {{ .replicasCount }}
  selector:
    matchLabels: {{- include "common.matchLabels" (dict "name" .name "release" $.Release) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .authTokenMaxValidity }}
        checksum/config: {{ .authTokenMaxValidity | quote | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 8 }}
    spec:
      {{- if $.Values.global.imageCredentials.username }}
      imagePullSecrets:
        - name: github-auth-secret
      {{- end }}
      containers:
      - name: {{ .name }}
        image: "{{ .image.url }}:{{ .image.tag }}"
        env:
          - name: GUACD_HOSTNAME
            value: {{ $.Values.guacd.name | quote }}
          - name: GUACD_PORT
            value: {{ (index $.Values.guacd.ports 0).port | quote }}
          - name: POSTGRESQL_USERNAME
            value: {{ $.Values.postgresServices.guacamole.dbUser | quote }}
          - name: POSTGRESQL_PASSWORD
            value: {{ $.Values.postgresServices.guacamole.dbPassword | quote }}
          - name: POSTGRESQL_HOSTNAME
            value: {{ $.Values.global.postgres.serviceName | quote }}
          - name: POSTGRESQL_DATABASE
            value: {{ $.Values.postgresServices.guacamole.dbName | quote }}
          - name: POSTGRESQL_PORT
            value: {{ $.Values.global.postgres.port | quote }}
          - name: LOGBACK_LEVEL
            value: DEBUG
        ports:
          {{- range .ports }}
          - containerPort: {{ .port }}
            name: guacapi-{{ .port }}
          {{- end }}
        readinessProbe:
          {{- range .ports }}
          {{- if and (eq .protocol "TCP") (.probe) }}
          tcpSocket:
            port: {{ .port }}
          initialDelaySeconds: 5
          periodSeconds: 10
          {{- end }}
          {{- end }}
        {{- if .environments}}
        env:
          {{- range .environments }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
        {{- end }}
      {{- if .authTokenMaxValidity }}
        volumeMounts:
          - name: guacamole-volume
            mountPath: /root
      volumes:
        - name: guacamole-volume
          persistentVolumeClaim:
            claimName: guacamole
      {{- end }}
{{- end }}
