{{- with .Values.guacamole }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}-hook-postinstall
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  containers:
    - name: {{ .name }}-post-install-job
      image: rancher/curl
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/sh"
        - "-c"
        - |
          apk update && apk add jq
          token=`curl -s -X POST -d 'username=guacadmin&password=guacadmin' http://{{ .name }}:8080/guacamole/api/tokens | jq -r '.authToken'`
          curl -s -X POST -H "Content-Type: application/json" -d '{"username":"{{ $.Values.global.guacamoleUser }}","password":"{{ $.Values.global.guacamoleUserPassword }}","attributes":{}}'\
           http://{{ .name }}:8080/guacamole/api/session/data/postgresql/users?token=$token
          curl -s -X POST -H "Content-Type: application/json" -d '{"username":"{{ .guacamoleAdmin }}","password":"{{ .guacamoleAdminPassword }}","attributes":{}}'\
           http://{{ .name }}:8080/guacamole/api/session/data/postgresql/users?token=$token
          curl -s -X PATCH -H "Content-Type: application/json" -d '[{"op":"add","path":"/userPermissions/{{ .guacamoleAdmin }}","value":"UPDATE"},{"op":"add","path":"/systemPermissions","value":"CREATE_USER"},{"op":"add","path":"/systemPermissions","value":"CREATE_USER_GROUP"},{"op":"add","path":"/systemPermissions","value":"CREATE_CONNECTION"},{"op":"add","path":"/systemPermissions","value":"CREATE_CONNECTION_GROUP"},{"op":"add","path":"/systemPermissions","value":"CREATE_SHARING_PROFILE"},{"op":"add","path":"/systemPermissions","value":"ADMINISTER"}]'\
           http://{{ .name }}:8080/guacamole/api/session/data/postgresql/users/{{ .guacamoleAdmin }}/permissions?token=$token
          new_token=`curl -s -X POST -d 'username={{ .guacamoleAdmin }}&password={{ .guacamoleAdminPassword }}' http://{{ .name }}:8080/guacamole/api/tokens | jq -r '.authToken'`
          curl -s -X DELETE http://{{ .name }}:8080/guacamole/api/session/data/postgresql/users/guacadmin?token=$new_token
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
{{- end }}
