{{- if .Values.guacamole.authTokenMaxValidity }}
apiVersion: batch/v1
kind: Job
metadata:
  name: guacamole-initializer
  annotations:
    reloader.stakater.com/auto: "true"
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  template:
    spec:
      containers:
      - name: initializer
        image: busybox
        command:
          - sh
          - -c
          - |
            max_retries=60
            retries=0
            FILE=/root/.guacamole/guacamole.properties
            while [ ! -f $FILE ] && [ $retries -lt $max_retries ]; do
              echo "Waiting for $FILE to become available..."
              sleep 5
              retries=$((retries + 1))
            done

            if [ -f "$FILE" ]; then
              if grep -q "^authTokenMaxValidity:" "$FILE"; then
                sed -i "s/^authTokenMaxValidity:.*/authTokenMaxValidity: {{ .Values.guacamole.authTokenMaxValidity | int }}/" "$FILE"
                echo "authTokenMaxValidity value updated."
              else
                echo "authTokenMaxValidity option not found. Adding it."
                echo "authTokenMaxValidity: {{ .Values.guacamole.authTokenMaxValidity | int }}" >> "$FILE"
              fi
            fi
        volumeMounts:
          - name: guacamole-volume
            mountPath: /root
      restartPolicy: Never
      volumes:
      - name: guacamole-volume
        persistentVolumeClaim:
          claimName: guacamole
  backoffLimit: 4
{{- end }}
