replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-answers-storage/answers-storage-service
  tag: v0.0.1

mounts:
  - name: answers-storage
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: answers-storage-configmap
  - name: tls
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: crczp-certs
