apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.services.angularFrontend.name }}-configmap
  labels: {{- include "common.labels" (dict "name" .Values.global.services.angularFrontend.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
data:
  config.json: |
    {
      "enableLocalMode": false,
      "defaultPageSize": 15,
      "polling": {
        "pollingPeriodShort": 3000,
        "pollingPeriodLong": 5000,
        "retryCount": 3
      },
      "basePaths": {
        "linearTraining": "https://{{ .Values.global.headHost }}{{ .Values.global.services.training.contextPath }}",
        "adaptiveTraining": "https://{{ .Values.global.headHost }}{{ .Values.global.services.adaptiveTraining.contextPath }}",
        "sandbox": "https://{{ .Values.global.headHost }}{{ .Values.global.services.sandbox.contextPath }}",
        "userAndGroup": "https://{{ .Values.global.headHost }}{{ .Values.global.services.userAndGroup.contextPath }}",
        "mitre": "https://{{ .Values.global.headHost }}{{ .Values.global.services.mitre.contextPath }}",
        "guacamole": "https://{{ .Values.global.headHost }}{{ .Values.global.services.guacamole.contextPath }}"
      },
      "roleMapping": {
        "uagAdmin": "ROLE_USER_AND_GROUP_ADMINISTRATOR",
        "trainingDesigner": "ROLE_TRAINING_DESIGNER",
        "trainingOrganizer": "ROLE_TRAINING_ORGANIZER",
        "adaptiveTrainingDesigner": "ROLE_ADAPTIVE_TRAINING_DESIGNER",
        "adaptiveTrainingOrganizer": "ROLE_ADAPTIVE_TRAINING_ORGANIZER",
        "trainingTrainee": "ROLE_TRAINING_TRAINEE",
        "sandboxDesigner": "ROLE_SANDBOX-SERVICE_DESIGNER",
        "sandboxOrganizer": "ROLE_SANDBOX-SERVICE_ORGANIZER"
      },
      "authConfig": {
        "guardMainPageRedirect": "home",
        "guardLoginPageRedirect": "login",
        "interceptorAllowedUrls": [
          "https://{{ .Values.global.headHost }}"
        ],
        "authorizationStrategyConfig": {
          "authorizationUrl": "https://{{ .Values.global.headHost }}{{ .Values.global.services.userAndGroup.contextPath }}users/info"
        },
        "navigateToRequestedRoutePostLogin": true,
        "providers": [
{{- range $index, $element := .Values.global.oidcProviders }}{{if $index}},{{end}}
          {
            "label": "{{ $element.label }}",
            "textColor": "white",
            "backgroundColor": "#002776",
            "oidcConfig": {
              "requireHttps": true,
              "issuer": "{{ $element.url }}",
              "clientId": "{{ $element.clientId }}",
              "redirectUri": "https://{{ $.Values.global.headHost }}",
              "scope": "openid email profile{{ if $element.refreshToken }} offline_access{{ end }}",
              "logoutUrl": "{{ $element.logoutUrl }}",
              "postLogoutRedirectUri": "https://{{ $.Values.global.headHost }}/logout-confirmed",
              "silentRefreshRedirectUri": "https://{{ $.Values.global.headHost }}/silent-refresh.html",
              "clearHashAfterLogin": true,
              "strictDiscoveryDocumentValidation": false,
              "skipIssuerCheck": true,
              {{- if $element.responseType }}
              "responseType": "{{ $element.responseType }}",
              {{- end }}
              "oidc": true
            }
          }
{{- end }}
        ]
      },
      "version": "{{ .Values.releaseVersion }}"
    }
