{{- $users := $.Values.global.users }}
{{- if (lookup "v1" "Secret" "crczp" "generated-users") }}
{{- $users = concat $.Values.global.users ((lookup "v1" "Secret" "crczp" "generated-users").data.generatedUsers | b64dec | fromYamlArray) }}
{{- end }}
{{- range $users }}
{{- if .keycloakPassword }}
---
apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakUser
metadata:
  name: {{ .keycloakUsername | replace "@" "-" }}
spec:
  realmRef:
    name: crczp-realm
  username: {{ .keycloakUsername }}
  definition:
    firstName: {{ .givenName }}
    lastName: {{ .familyName }}
    email: {{ .email }}
    enabled: true
    emailVerified: false
  realmRoles:
    - offline_access
  initialPassword:
    value: {{ .keycloakPassword | quote }}
    temporary: false
{{- end }}
{{- end }}
