apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakClient
metadata:
  name: crczp-client
spec:
  realmRef:
    name: crczp-realm
  clientId: {{ range $.Values.global.oidcProviders }}{{- if contains "keycloak" .url }}{{ .clientId }}{{- end }}{{- end }}
  definition:
    name: "CRCZP-Client"
    protocol: openid-connect
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    {{- if .Values.development }}
    implicitFlowEnabled: true
    {{- else }}
    implicitFlowEnabled: false
    {{- end }}
    attributes:
      pkce.code.challenge.method: S256
      post.logout.redirect.uris: +
    redirectUris:
      - "https://{{ $.Values.global.headHost }}"
      - "https://{{ $.Values.global.headHost }}/login"
      - "https://{{ $.Values.global.headHost }}/index.html"
      - "https://{{ $.Values.global.headHost }}/silent-refresh.html"
      {{- if .Values.development }}
      - "https://localhost:4200"
      {{- end }}
    defaultClientScopes:
      - email
      - profile
      - openid
    optionalClientScopes:
      - offline_access
