{{- if .Values.global.imageCredentials.username }}
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secret
  labels: {{- include "common.labels" (dict "name" .Values.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  .dockerconfigjson: {{ template "common.imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}
