replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-sandbox-service/sandbox-service
  tag: v1.1.0

environments:
  SERVICE_PRECONDITION: "uag-service:8084"
  DJANGO_ADMIN_USER: crczp-admin
  DJANGO_ADMIN_PASSWORD:
  DJANGO_ADMIN_EMAIL: crczp-admin@example.com

mounts:
  config:
    extension: .yml
    mountPath: /app/
    isOneFile: true
    subPath: true
    type:
      secret:
        secretName: sandbox-service-secret
  tls:
    extension: .crt
    mountPath: /usr/local/share/ca-certificates/
    isOneFile: true
    subPath: true
    type:
      secret:
        secretName: crczp-certs
  proxy-key:
    extension: ""
    mountPath: /root/.ssh/
    isOneFile: true
    subPath: true
    mode: '0600'
    type:
      secret:
        secretName: proxy-key
  ansible-runner-vol:
    extension: ""
    mountPath: /var/opt/crczp/ansible-runner-volumes
    isOneFile: false
    type:
      persistentVolumeClaim:
        claimName: sandbox-service

pvc:
  enabled: true
  size: 1Gi
  storageClassName: local-path
  accessMode: ReadWriteOnce

stackNamePrefix: default0
dnsNameServers:
  - 1.1.1.1
  - 1.0.0.1
osAuthUrl:
osApplicationCredentialId:
osApplicationCredentialSecret:
osConsoleType: spice-html5
openstackWorkerCount: 4
ansibleWorkerCount: 4
defaultWorkerCount: 4
sandboxBuildTimeout: 7200
sandboxDeleteTimeout: 3600
sandboxAnsibleTimeout: 7200
manFlavor: standard.small
manImage: debian-12-x86_64
manUser: debian
proxyHost:
proxyUser:
proxyKey:
proxyPort:
ansibleDockerNetwork: host
djangoSecretKey:
flavorMapping: {}

smtpServer:
smtpPort: 25
senderEmail: "sandbox.service@crczp.cz"
senderEmailPassword:
smtpEncryption:

redis:
  defaultCacheTimeout: 86400
  uagCacheTimeout: 86400
  topologyCacheTimeout: 86400

ansibleRunner:
  image:
    url: ghcr.io/cyberrangecz/crczp-ansible-runner
    tag: 1.0.0

gitConfig:
  providers: {}
  #providers: {"https://github.com/": "TOKEN"}
  user: git
  ansibleNetworkingUrl: https://github.com/cyberrangecz/ansible-stage-one.git
  ansibleNetworkingRev: v1.0.0

aws:
  accessKeyId:
  secretAccessKey:
  region: eu-central-1
  availabilityZone: eu-central-1a
  baseVpc: BaseNet
  baseSubnet: BaseSubnetA

keystoneCA:
