{{- if and (not (and .Values.global.tlsPrivateKey .Values.global.tlsPublicKey)) (.Values.selfSigned) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  labels: {{- include "common.labels" (dict "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.tlsSecretName }}
  labels: {{- include "common.labels" (dict "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
spec:
  secretName: {{ .Values.global.tlsSecretName }}
  dnsNames:
    - {{ .Values.global.headHost }}
  commonName: {{ .Values.global.headHost }}
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}
