apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.services.mitre.name }}-secrets
  labels: {{- include "common.labels" (dict "name" .Values.global.services.mitre.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
type: Opaque
data:
  djangoSecretKey: {{ required "djangoSecretKey is required" .Values.djangoSecretKey | b64enc }}
