replicasCount: 1

image:
  url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-sandbox-service
  tag: 23.12

environments:
  - name: SERVICE_PRECONDITION
    value: uag-service:8084

mounts:
  - name: config
    extension: .yml
    mountPath: /app/
    isOneFile: true
    subPath: true
    type:
      secret:
        secretName: sandbox-service-secret
  - name: tls
    extension: .crt
    mountPath: /usr/local/share/ca-certificates/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: kypo-certs
  - name: kypo-crp-proxy-key
    extension:
    mountPath: /root/.ssh/
    isOneFile: true
    subPath: true
    mode: 0600
    type:
      secret:
        secretName: kypo-crp-proxy-key
  - name: ansible-runner-vol
    extension:
    mountPath: /var/opt/kypo/kypo-ansible-runner-volumes
    isOneFile: false
    type:
      persistentVolumeClaim:
        claimName: sandbox-service

pvc:
  size: 1Gi
  storageClassName: local-path
  accessMode: ReadWriteOnce

kypoHeadIp: 0.0.0.0
stackNamePrefix: default0
dnsNameServers:
  - 1.1.1.1
  - 1.0.0.1
osAuthUrl:
osApplicationCredentialId:
osApplicationCredentialSecret:
osConsoleType: spice-html5
openstackWorkerCount: 4
ansibleWorkerCount: 4
defaultWorkerCount: 4
sandboxBuildTimeout: 7200
sandboxDeleteTimeout: 3600
sandboxAnsibleTimeout: 7200
manFlavor: csirtmu.tiny1x2
manImage: debian-11-man-0.1.0
proxyHost:
proxyUser:
proxyKey:
ansibleDockerNetwork: host
smtpServer:
smtpPort: 25
senderEmail: "sandbox.service@kypo.cz"
senderEmailPassword:

ansibleRunner:
  image:
    url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-ansible-runner
    tag: 23.04

gitConfig:
  type: INTERNAL
  server: git-internal.kypo
  sshPort: 22
  restServerUrl: http://git-internal.kypo:5000/
  user: git
  privateKey:
  accessToken: no-gitlab-token
  ansibleNetworkingUrl: git@git-internal.kypo:/repos/backend-python/ansible-networking-stage/kypo-ansible-stage-one.git
  ansibleNetworkingRev: v1.0.14
