{{- $ports := list (dict "port" .Values.global.services.sandbox.port "protocol" "TCP" "probe" true) -}}
{{- include "common.deployment.header" (dict "name" .Values.global.services.sandbox.name "replicasCount" .Values.replicasCount "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.services.sandbox.name "ports" $ports "Values" .Values "command" "/app/bin/run-sandbox-service.sh") }}
            - name: git-ssh-key
              mountPath: "/root/.ssh/git-ssh-key"
              subPath: "git-ssh-key"
          lifecycle:
            postStart:
              exec:
                command:
                  - update-ca-certificates
{{- include "common.deployment.volumes" (dict "Values" .Values) }}
        - name: git-ssh-key
          secret:
            {{- if .Values.gitConfig.privateKey }}
            secretName: git-external-key
            {{- else }}
            secretName: git-internal-key
            {{- end }}
            items:
              - key: "git-ssh-key"
                path: "git-ssh-key"
                mode: 0400
