image:
  url: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.1.2

ports:
  - port: 9200
    protocol: TCP
    probe: true
  - port: 9300
    protocol: TCP
    probe: true

environments:
  node.name: es01
  bootstrap.memory_lock: true
  discovery.type: single-node
  ES_JAVA_OPTS: -Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true
  cluster.max_shards_per_node: 5000
  xpack.security.enabled: false
  action.destructive_requires_name: false

mounts:
  data-elasticsearch:
    mountPath: /usr/share/elasticsearch/data
    type:
      persistentVolumeClaim:
        claimName: crczp-elasticsearch

pvc:
  size: 500Mi

numberOfShards: 1
numberOfReplicas: 0
indexRefreshInterval: "5s"
