kypo-oidc:
  enabled: True

global:
  headHost: 172.19.0.22
  tlsSecretName: kypo-certs
  kypoSyslogServiceName: kypo-syslog-ng
  kypoLogstashServiceName: kypo-logstash
  kypoElasticsearchServiceName: kypo-elasticsearch
  kypoElasticsearchServiceIndexMaxResultWindow: 30000
  guacamoleUser: guac-user
  guacamoleUserPassword: guac-user
  kypoTerraformBackendType: 'kubernetes'
  corsWhitelist:

  oidcProviders:
    - url:
      logoutUrl:
      clientId:
      label:
      issuerIdentifier:
      userInfoUrl:

  redis:
    serviceName: kypo-redis
    port: 6379
    db: 0

  postgres:
    serviceName: postgres
    port: 5432
    user: postgres
    password: password

  postgresServices:
    adaptiveTraining:
      dbName: kypo-adaptive-training
      dbUser: kypo-adaptive-training
      dbPassword: kypo-adaptive-training
    answersStorage:
      dbName: kypo-answers-storage
      dbUser: kypo-answers-storage
      dbPassword: kypo-answers-storage
    sandbox:
      dbName: sandbox-service
      dbUser: sandbox-service
      dbPassword: sandbox-service
    smartAssistant:
      dbName: kypo-adaptive-smart-assistant
      dbUser: kypo-adaptive-smart-assistant
      dbPassword: kypo-adaptive-smart-assistant
    training:
      dbName: training
      dbUser: training
      dbPassword: training
    trainingFeedback:
      dbName: kypo-training-feedback
      dbUser: kypo-training-feedback
      dbPassword: kypo-training-feedback
    userAndGroup:
      dbName: user-and-group
      dbUser: user-and-group
      dbPassword: user-and-group

  services:
    angularFrontend:
      name: angular-frontend
      port: 8000
      contextPath: /
    adaptiveTraining:
      name: adaptive-training-service
      port: 8082
      contextPath: /kypo-adaptive-training/api/v1/
    answersStorage:
      name: answers-storage
      port: 8087
      contextPath: /kypo-answers-storage/api/v1/
    elasticsearch:
      name: elasticsearch-service
      port: 8085
      contextPath: /kypo-elasticsearch-service/api/v1/
    mitre:
      name: mitre-service
      port: 8001
      contextPath: /kypo-mitre-technique-service/api/v1/
    sandbox:
      name: sandbox-service
      port: 8000
      contextPath: /kypo-sandbox-service/api/v1/
    smartAssistant:
      name: smart-assistant
      port: 8086
      contextPath: /kypo-adaptive-smart-assistant/api/v1/
    training:
      name: training-service
      port: 8083
      contextPath: /kypo-rest-training/api/v1/
    trainingFeedback:
      name: training-feedback-service
      port: 8088
      contextPath: /kypo-training-feedback/api/v1/
    userAndGroup:
      name: uag-service
      port: 8084
      contextPath: /kypo-rest-user-and-group/api/v1/
      staticIngress: True
