apiVersion: v2
name: kypo-guacamole
description: Guacamole Helm chart used by KYPO CRP head services
type: application
version: 1.0.1
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
