apiVersion: v2
name: crczp-guacamole
description: Guacamole Helm chart used by head services
type: application
version: 1.0.1
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
