guacd:
  name: guacd
  image:
    url: guacamole/guacd
    tag: 1.6.0
  ports:
    - port: 4822
      protocol: TCP
      probe: true
  pvc:
    size: 500Mi

guacamole:
  name: guacamole
  replicasCount: 1
  image:
    url: ghcr.io/cyberrangecz/backend-guacamole/backend-guacamole/service
    tag: v1.0.0
  environments:
    - name: SERVICE_PRECONDITION
      value: uag-service:8084
  mounts:
    - name: guacamole
      extension: .properties
      mountPath: /app/etc/
      isOneFile: true
      subPath: false
      type:
        configMap:
          name: guacamole-service-configmap
    - name: tls
      extension: .crt
      mountPath: /srv/
      isOneFile: true
      subPath: false
      type:
        secret:
          secretName: crczp-certs
