postgresServices:
  guacamole:
    dbName: crczp_guacamole_db
    dbUser: crczp_guacamole_user
    dbPassword: crczp_password

guacd:
  name: guacd
  image:
    url: guacamole/guacd
    tag: 1.3.0
  ports:
    - port: 4822
      protocol: TCP
      probe: true
  pvc:
    size: 500Mi

guacamole:
  name: guacamole
  replicasCount: 1
  image:
    url: ghcr.io/cyberrangecz/backend-guacamole-quickconnect
    tag: 1.3.0
  ports:
    - port: 8080
      protocol: TCP
      probe: true
  guacamoleAdmin: guac-admin
  guacamoleAdminPassword: guac-admin
  authTokenMaxValidity:


pvc:
  size: 1Mi
  storageClassName: local-path
  accessMode: ReadWriteOnce
