replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-answers-storage/answers-storage-service
  tag: v1.0.0

mounts:
  guacamole-service:
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: guacamole-service-configmap
  tls:
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: crczp-certs

