apiVersion: v2
name: kypo-git-internal
description: Internal Git Helm chart used by KYPO CRP head services
type: application
version: 1.1.0
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
