{{- include "common.deployment.header" (dict "name" .Values.global.crczpElasticsearchServiceName "strategy" "Recreate" "replicasCount" 1 "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.crczpElasticsearchServiceName "ports" .Values.ports "Values" .Values) }}
      initContainers:
        - name: change-ownership-container
          image: busybox
          command: ["/bin/chown","-R","1000:1000", "/usr/share/elasticsearch/data"]
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: data-elasticsearch
              mountPath: /usr/share/elasticsearch/data
{{- include "common.deployment.volumes" (dict "Values" .Values) }}
