replicasCount: 1

image:
  url: ghcr.io/cyberrangecz/backend-adaptive-smart-assistant/adaptive-smart-assistant-service
  tag: v1.0.0

mounts:
  adaptive-smart-assistant:
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: smart-assistant-configmap
