apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-initial-admin
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
data:
  username: {{ .Values.keycloakAdmin | b64enc }}
  password: {{ .Values.keycloakPassword | b64enc }}
type: kubernetes.io/basic-auth
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.name }}
  labels: {{- include "common.labels" (dict "name" .Values.name "chart" $.Chart "release" $.Release "extraLabels" $.extraLabels) | nindent 4 }}
spec:
  instances: 1
  db:
    vendor: postgres
    host: {{ $.Values.global.postgres.serviceName }}
    port: {{ $.Values.global.postgres.port }}
    database: {{ .Values.db.database }}
    usernameSecret:
      name: {{ .Values.name }}-secrets
      key: username
    passwordSecret:
      name: {{ .Values.name }}-secrets
      key: password
  features:
    enabled:
      - hostname:v1
  http:
    httpEnabled: true
    httpPort: 8080
  ingress:
    enabled: false
  hostname:
    hostname: {{ $.Values.global.headHost }}
  additionalOptions:
    - name: proxy
      value: edge
    - name: hostname-path
      value: /keycloak
    - name: http-relative-path
      value: /keycloak
