apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  labels: {{- include "common.labels" (dict "name" .Values.name "chart" $.Chart "release" $.Release "extraLabels" .Values.extraLabels) | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  username: {{ .Values.db.username | b64enc }}
  password: {{ randAlpha 20 | b64enc }}

