{{- define "common.labels" -}}
app.kubernetes.io/name: {{ .name }}
helm.sh/chart: {{ .chart.Name }}-{{ .chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .release.Service }}
app.kubernetes.io/instance: {{ .release.Name }}
app.kubernetes.io/part-of: CyberRangeCZ-Platform
{{- range $key, $val := .extraLabels }}
{{ $key }}: {{ $val }}
{{- end}}
{{- end -}}

{{- define "common.matchLabels" -}}
app.kubernetes.io/name: {{ .name }}
app.kubernetes.io/instance: {{ .release.Name }}
{{- end -}}

{{- define "common.imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.global.imageCredentials.registry (printf "%s:%s" .Values.global.imageCredentials.username .Values.global.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
