{{- if .Values.global.userCount }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: generated-users
  labels: {{- include "common.labels" (dict "name" .Chart.Name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
stringData:
  generatedUsers: |
    {{- range untilStep 1 ( .Values.global.userCount | add1 | int ) 1 }}
    - sub: user-{{ . }}
      iss: 'https://{{ $.Values.global.headHost }}/keycloak/realms/KYPO'
      password: {{ randAlphaNum 10 }}
      email: user{{ . }}@kypo
      fullName: "User{{ . }} Generated"
      givenName: "User{{ . }}"
      familyName: "Generated"
      admin: False
    {{- end }}
{{- end }}
